#!/bin/bash
# Installs a pre-commit git hook.

function install {
  HOOK_SOURCE="vendor/xzito/styleguide/scripts/pre-commit"

  local project_root; project_root="$(git rev-parse --show-toplevel)"
  local hook="$project_root/.git/hooks/pre-commit"

  echo "* Checking for an existing pre-commit hook..."

  if [ -e "$project_root/.git/hooks/pre-commit" ]; then
    local backup_file; backup_file="_$(date +%s)_pre-commit"
    local hook_backup="$project_root/$backup_file"

    echo "*"
    echo "* pre-commit hook already exists."
    echo "*"
    echo "* Making a backup of the existing hook in:"
    echo "*   $hook_backup"

    cp "$hook" "$hook_backup"
  fi

  echo "*"
  echo "* Creating pre-commit hook..."

  cp "$HOOK_SOURCE" "$hook"
  chmod +x "$hook"

  echo "*"
  echo "* Hook installed..."
}

install
